[package]
name = "isideload-apple-bundles"
version = "0.21.0"
authors = ["Nicholas Sharp <nab@nabdev.me>"]
edition = "2021"
rust-version = "1.81"
license = "MPL-2.0"
description = "Interface with Apple bundle primitives"
keywords = ["apple", "macos", "bundle", "appbundle"]
homepage = "https://github.com/nab138/isideload-apple-platform-rs"
repository = "https://github.com/nab138/isideload-apple-platform-rs.git"
readme = "README.md"

[dependencies]
anyhow = "1.0.93"
isideload-vfs = { version = "0.0.1", path = "../isideload-vfs" }
plist = "1.7.0"
simple-file-manifest = { version = "0.11.0", path = "../simple-file-manifest-rs", package = "isideload-simple-file-manifest" }
walkdir = { version = "2.5.0", package = "isideload-walkdir", path = "../walkdir" }


[dev-dependencies]
tempfile = "3.14.0"
